### ISSUE TITLE
False error on login

### ISSUE THREAD

**Issue by jdungan** [codesy/codesy#584] opened 2018-03-14 16:04 UTC
Clicked "sign in with github" got this page but I'm logging in.

<img width="1680" alt="screen shot 2018-03-14 at 11 02 44 am" src="https://user-images.githubusercontent.com/1707538/37414537-54865150-2777-11e8-973c-1b23296c1bb4.png">

**Comment by groovecoder** [comment] 2018-05-28 15:52
Dupe of #599.

**Closed by groovecoder** 2018-05-28 15:52 UTC
