### ISSUE TITLE
rename Claim.claimant to Claim.user

### ISSUE THREAD

**Issue by FreeHooks** [codesy/codesy#166] opened 2015-03-19 01:58 UTC
File: https://github.com/codesy/codesy/blob/f473abc395c063cef22972b2b44d20aebb1f0a5f/auctions/models.py#L102

**Comment by jdungan** [comment] 2016-02-24 00:34
This is a duplicate of #203 and is fixed.

**Closed by jdungan** 2016-02-24 00:34 UTC
